name: Test Concurrency
on:
  push:
  workflow_dispatch:
concurrency:
  group: ${{ matrix.product }}
  cancel-in-progress: false
jobs:
  execute:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alias: [alpha, beta, gamma]
        product: [one, two]
    steps:
      - name: Execute Code
        run: |
          echo 'The product is:'
          echo ${{ matrix.product }}
          echo 'The alias is:'
          echo ${{ matrix.alias }}
